version: "3"

services:
  app:
    build: .
    tty: true
    restart: always
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app
    ports:
      - "80:80"
      - "433:443"
    # command: /bin/bash -c "/install/serve.sh *:80 lv.test /var/www/app/public && /usr/bin/env bash start;sleep infinity"
    links:
      - db

  db:
    image: mysql:5.7
    restart: always
    command: ["mysqld", "--character-set-server=utf8", "--collation-server=utf8_general_ci", "--skip-character-set-client-handshake"]
    volumes:
      - ./.docker/mysql:/var/lib/mysql
      - ./.docker/mysql-files:/var/lib/mysql-files/
      - ./.docker/data:/var/data
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_USER_CONFIG_BASE64: PD9waHAKJGNmZ1snTG9naW5Db29raWVWYWxpZGl0eSddID0gODY0MDA7
